### PR TITLE
Hardware::CPU.type: check uname -m

### LINKED ISSUE #336: Hardware::CPU.type should check `uname -m`
If running brew inside a Raspberry Pi docker container, `Hardware::CPU.type` will report incorrect arch type. In my case, it will return `intel` instead of `arm`. The is because `/etc/cpuinfo` will report the host CPU type. It would be better to check `uname -m` for better hardware detection, especially when the host and VM have different CPU architectures.

### PR DESCRIPTION
**Pull request by xu-cheng**
Determining CPU type by reading `/proc/cpuinfo` is less reliable than
checking the value of `uname -m`. Particularly, `/proc/cpuinfo` often
return the CPU info for the host CPU when running Linuxbrew inside a VM.
Therefore, if the host and VM share different CPU architectures,
`/proc/cpuinfo` will return incorrect result.

To fix the problem, checking `uname -m` first, otherwise fallback to
`/proc/cpuinfo`.

Fixes #336.

### CODE REVIEW

File: Library/Homebrew/extend/os/linux/hardware/cpu.rb [hunk 1]
```diff
@@ -20,12 +20,19 @@ def cpuinfo
...
+        @type ||= begin
+          uname = Utils.popen_read("uname", "-m").chomp
+          if uname == "x86_64"
+            :intel
+          elsif uname.start_with? "arm"
+            :arm
+          elsif cpuinfo =~ /Intel|AMD/
+            :intel
+          elsif cpuinfo =~ /ARM|Marvell/
+            :arm
```
Comment (sjackman) [inline Library/Homebrew/extend/os/linux/hardware/cpu.rb]: I'm not a fan of the redundancy. I did imply that's what I wanted. Sorry for that.

Let's delete lines 29–32 until we find a situation where they're necessary. What does `uname -m` return on a 32-bit x86 system? As I recall it matches `/86$/`, like `i386`, `i586` et c.
I oddly can't find the original issue for the `Marvel` ARM system. I'm fine ignoring that for now.
Let's use
```ruby
case Utils.popen_read("uname", "-m").chomp
```

**Review by sjackman — CHANGES_REQUESTED** [review]
Minor changes requested. Works for me, in principle. Thanks again, Xu.

File: Library/Homebrew/extend/os/linux/hardware/cpu.rb (hunk 1 above)
Comment (xu-cheng) [reply Library/Homebrew/extend/os/linux/hardware/cpu.rb]: Updated

**Review by sjackman — APPROVED** [review]

**Comment by sjackman** [comment]
Thanks again for your contribution to Linuxbrew, Xu!
